### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by baudehlo** [sonaye/react-native-behavior#11]
Hi,

We've been using the Haraka name for around 7 or 8 years now. Can you please pick a new name? Thanks.

https://haraka.github.io/
https://www.npmjs.com/package/Haraka
https://en.wikipedia.org/wiki/Haraka_(software)
https://github.com/haraka/Haraka

**Comment by sonaye** [comment]
Hi,

The name was available on npm, I honestly didn’t know that npm names are case sensitive.

I cannot afford changing the name at the moment because we’re building a product on top of it at the moment, changing the name would be a breaking change.

I doubt that anyone would confuse a mail server with an animation library. I will however look into this, I can assure you that. I do realize now that the name belongs to you.

I would appreciate your patience here. Thanks.

**Comment by baudehlo** [comment]
No problem, take your time. I'm mostly trying to help you: searching for
Haraka will usually bring up our project since it's been around for so long.

**Comment by msimerson** [comment]
I just discovered this today, when I got the wrong Haraka installed with `npm i haraka`. 

Before finding this issue I initiated correspondence with NPM regarding this as I feel variations in name case should not be publishable on NPM. It permits typo-squatting and other such security issues we've observed at the TLDs. If NPM revokes your package from the registry, that will be why.

Interestingly enough, we also own the [haraka NPM org](https://www.npmjs.com/org/haraka) which also wasn't enough to prevent this namespace collision.

**Comment by msimerson** [comment]
I forgot to mention, @sonaye could continue using the haraka name by publishing it within a scoped namespace such as `@sonaye/haraka`. I would not object to that.

**Comment by sonaye** [comment]
I will be moving it to `@exodus/haraka`, contacted npm to make the name available for you. I will reach out to you through email @baudehlo once the name is cleared.

**Comment by sonaye** [comment]
From npm:

> As requested, the haraka package has been transferred to the @haraka org.
